[blog]
title = "Nano Memories"

[article.hello]
ru = { title = "Какой-то заголовок!" }
en = { title = "Some title!" }

[[social]]
href = "https://github.com/nanoqsh"
icon = "gh"

[[social]]
href = "https://bsky.app/profile/nanoqsh.bsky.social"
icon = "bs"

[[social]]
href = "https://discord.com/users/589014218498375680"
icon = "ds"

[[social]]
href = "mailto:nanoqsh@gmail.com"
icon = "em"
