[article.hello]
title = "Some title!"

[[social]]
href = "https://github.com/nanoqsh"
icon = "gh"

[[social]]
href = "https://x.com/nanoqsh"
icon = "x"

[[social]]
href = "https://discord.com/users/589014218498375680"
icon = "ds"
